spring:
    cloud:
        gateway:
            routes:
                - id: user-service
                  uri: https://0fef070d-7df6-4bea-8793-079e51720078.mock.pstmn.io
                  predicates:
                    - Path=/users/**
                
                - id: order-service
                  uri: https://56e0e30a-1376-4936-894e-cbd00c76258a.mock.pstmn.io
                  predicates:
                    - Path=/orders/**
               